### ISSUE TITLE
Exception when connecting to end-point

### ISSUE THREAD

**Issue by pankleks** [node-opcua/opcua-commander#22] opened 2020-02-18 10:05 UTC
Hello, I have following expection when trying to connect:

![image](https://user-images.githubusercontent.com/14176066/74725625-7275e380-523e-11ea-82cf-21d8e2e5b9a2.png)

**Comment by erossignon** [comment] 2020-03-20 18:46
Duplicate of #23

**Closed as completed by erossignon** 2020-03-20 18:46 UTC
